package com.livingmetal.salarytimer
import android.content.*; import android.os.Bundle; import androidx.activity.ComponentActivity; import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*; import androidx.compose.material3.*; import androidx.compose.runtime.*; import androidx.compose.ui.*; import androidx.compose.ui.text.font.FontWeight; import androidx.compose.ui.unit.*
import kotlinx.coroutines.delay; import java.time.*; import java.time.temporal.ChronoUnit; import java.text.NumberFormat; import java.util.Locale
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{MaterialTheme{App(this)}}}}
@Composable fun App(ctx:Context){
 val p=ctx.getSharedPreferences("s",0); var annual by remember{mutableStateOf(p.getLong("annual",100000000).toString())}; var payday by remember{mutableStateOf(p.getInt("payday",25).toString())}; var start by remember{mutableStateOf(p.getString("start","09:00")!!)}; var end by remember{mutableStateOf(p.getString("end","18:00")!!)}; var lunch by remember{mutableStateOf(p.getInt("lunch",60).toString())}; var edit by remember{mutableStateOf(false)}; var now by remember{mutableStateOf(LocalDateTime.now())}
 LaunchedEffect(Unit){while(true){now=LocalDateTime.now();delay(1000)}}
 if(edit) Column(Modifier.padding(24.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("월급 타이머 설정",fontSize=28.sp,fontWeight=FontWeight.Bold); OutlinedTextField(annual,{annual=it.filter(Char::isDigit)},label={Text("세전 연봉 (원)")});OutlinedTextField(payday,{payday=it.filter(Char::isDigit)},label={Text("급여일")});OutlinedTextField(start,{start=it},label={Text("출근 HH:mm")});OutlinedTextField(end,{end=it},label={Text("퇴근 HH:mm")});OutlinedTextField(lunch,{lunch=it.filter(Char::isDigit)},label={Text("휴게시간(분)")});Button({p.edit().putLong("annual",annual.toLongOrNull()?:0).putInt("payday",(payday.toIntOrNull()?:25).coerceIn(1,31)).putString("start",start).putString("end",end).putInt("lunch",lunch.toIntOrNull()?:60).apply();edit=false}){Text("저장")}}
 else {val a=annual.toLongOrNull()?:0;val st=runCatching{LocalTime.parse(start)}.getOrDefault(LocalTime.of(9,0));val en=runCatching{LocalTime.parse(end)}.getOrDefault(LocalTime.of(18,0));val ws=(Duration.between(st,en).seconds-(lunch.toIntOrNull()?:60)*60).coerceAtLeast(1);val rate=a/(ws*260.0);val t=now.toLocalTime();var elapsed=if(now.dayOfWeek.value<=5&&t>st)Duration.between(st,minOf(t,en)).seconds.toDouble() else 0.0;val ls=LocalTime.NOON;val le=ls.plusMinutes((lunch.toLongOrNull()?:60));if(t>ls)elapsed-=Duration.between(ls,minOf(t,le)).seconds;elapsed=elapsed.coerceIn(0.0,ws.toDouble());val earned=elapsed*rate;val won=NumberFormat.getNumberInstance(Locale.KOREA);val d=payday.toIntOrNull()?:25;var pd=now.toLocalDate().withDayOfMonth(d.coerceAtMost(now.toLocalDate().lengthOfMonth()));if(pd.isBefore(now.toLocalDate())){val n=now.toLocalDate().plusMonths(1);pd=n.withDayOfMonth(d.coerceAtMost(n.lengthOfMonth()))}
 Scaffold(topBar={TopAppBar(title={Text("월급 타이머")},actions={TextButton({edit=true}){Text("설정")}})}){pad->Column(Modifier.padding(pad).padding(24.dp).fillMaxSize(),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(18.dp)){Spacer(Modifier.height(40.dp));Text("오늘도 벌고 있습니다");Text("₩ "+won.format(earned.toLong()),fontSize=42.sp,fontWeight=FontWeight.Bold);Text("+ ₩ "+"%.2f".format(rate)+" / 초");LinearProgressIndicator(progress={ (elapsed/ws).toFloat() },modifier=Modifier.fillMaxWidth());Text("오늘 근무 "+"%.1f".format(elapsed/ws*100)+"%");HorizontalDivider();Text("월급일까지 D-"+ChronoUnit.DAYS.between(now.toLocalDate(),pd));Spacer(Modifier.weight(1f));Text("연봉을 주 5일·연 52주 실근무시간에 균등 배분한 참고 지표입니다.",fontSize=11.sp)}}}
 }
}